### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by mickaphd** [naveednajam/Little-Snitch---Rule-Groups#6]
Hi there, very nice script. Works nicely but I don't understand how we can "subscribe" to the files as it is clearly not possible for security questions to add "lsrules" files as you can read here by the devs (https://forums.obdev.at/viewtopic.php?t=11360).
Thank you

**Comment by naveednajam** [comment]
Copy the link to raw file which is https url (secure) and dirctly paste in group subscription url place. 
For example blow is the url for first file in base url folder.

(https://github.com/naveednajam/Little-Snitch---Rule-Groups/blob/master/unified_hosts_base/stevenblack0.lsrules?raw=true)

What people is talking about in your mentioned link (https://forums.obdev.at/viewtopic.php?t=11360) are two different topics. 
**One is authenticity of rules and its maintainer.** 
This is very much debatable and relative. For example how much do you trust Apple, Google, Microsoft or any other company including obdev with their softwares. Don't you think it might be possible to have built in back doors in their own software/operating system. but we have to trust them. or the hard way is to compile everything by ourself which is not practical. In term of group rules you can maintain your own rules or at least can audit them to make sure no one is exploiting your security by removing or adding custom rules. 

**Second is how much control little snitch provides group rules.** 
For any modified deny rules in rule group by default is unapproved means it is marked with a blue dot in front of it. Secondly you can select to disable new allow rules in any rule group subscription which is added security. 
People are saying it will be better if rules can be subscribed per application it is purely possible in the lsrules file you can actually select any application you want instead of any process which means to all process. 
time based rule management is not really necessary for a desktop PC unless it is behaving as internet gateway and controlling access for large number of users where time based rules make more sense. One can always have different profiles for different user on same desktop machine which actually makes more sense.

**Comment by mickaphd** [comment]
Thanks much!
